### ISSUE TITLE
SetupWizard Force Close

### ISSUE THREAD

**Issue by ConradGyllenhaal** [BiTGApps/BiTGApps-Files#1]
Hello there,

Since many months I'm building CHAOSP ROM which uses your BiTGApps aosp⁻build project to include gapps, and everything works as intended.

Yesterday I did build CHAOSP for my device, the build was successful and flashed on the device.

But now, I got SetupWizard force closing.

Since they weren't any changes to CHAOSP since my last build (which didn't have this problem), I narrowed the issue to BiTGApps.

Indeed, on the last few days, you seem to have committed stuff linked to SetupWizard, so it could be linked.

Here is the adb logcat corresponding to the error:
```

10-20 11:42:29.482  4663  4663 D AndroidRuntime: Shutting down VM
10-20 11:42:29.483  4663  4663 E AndroidRuntime: FATAL EXCEPTION: main
10-20 11:42:29.483  4663  4663 E AndroidRuntime: Process: com.google.android.setupwizard, PID: 4663
10-20 11:42:29.483  4663  4663 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.android.setupwizard.SetupWizardApplication: java.lang.SecurityException: WifiService: Permission denied
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6724)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: Caused by: java.lang.SecurityException: WifiService: Permission denied
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2357)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2340)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2282)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.net.wifi.IWifiManager$Stub$Proxy.getCurrentNetwork(IWifiManager.java:3133)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.net.wifi.WifiManager.getCurrentNetwork(WifiManager.java:4993)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at com.android.settingslib.compat.WifiManagerImpl.getCurrentNetwork(PG:1)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at ls.a(PG:1)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at com.android.settingslib.wifi.WifiTracker.b(PG:3)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at avx.b(PG:1)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at att.a(PG:15)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at com.google.android.setupwizard.SetupWizardApplication.onCreate(PG:29)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	... 8 more
10-20 11:42:29.483  4663  4663 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at com.android.server.wifi.WifiServiceImpl.getCurrentNetwork(WifiServiceImpl.java:3500)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.net.wifi.IWifiManager$Stub.onTransact(IWifiManager.java:1192)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1123)
10-20 11:42:29.483  4663  4663 E AndroidRuntime: 
```

I'm eager to find a solution to fix this.

Regards!

**Comment by TheHitMan7** [comment]
You can also fix this by simply removing AndroidMigratePrebuilt & SetupWizardPrebuilt from system. I will remove SetupWizard from my aosp-build system. Some of the packages should be disabled, when using google's SetupWizard.

**Comment by ConradGyllenhaal** [comment]
Ok, the error isn't present anymore but I still get the Android Setup application that, if I remember correctly, wasn't present before.

This is the application responsible for the annoying notification about "Finish your phone setup" that propose you to copy date from previous/other phone, etc.
